sudo: required
services:
  - docker
before_install:
  - docker build  -t shahar/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true shahar/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket: "elasticbeanstalk-us-east-2-689537281203"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "AKIA2BC475SZWMJJZ2KW"
  secret_access_key: "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"
  
  